version: '3'

services:
  backend:
    build: ./server/cats/
    restart: always
    ports:
      - "3000:3000"
    networks:
      - cats_network

  frontend:
    depends_on:
      - backend
    build: ./client/cats/
    restart: always
    ports:
      - "4200:80"
    networks:
      - cats_network
networks:
 cats_network: